use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;
use sha2::{Digest, Sha256};

#[derive(Debug, Clone)]
struct Meta {
    fixed_len: Option<u8>,
    components: Vec<Component>,
    title: Option<String>,
    fnc1_required: bool,
    dl_data_attr: bool,
    dl_primary_key: bool,
    dl_qualifiers: Option<String>,
    req_rules: Vec<ReqClause>,
    ex_rules: Vec<String>,
}

type ReqGroup = Vec<String>;
type ReqClause = Vec<ReqGroup>;

#[derive(Debug, Clone, Deserialize)]
struct DictionaryLock {
    upstream_repo: String,
    upstream_ref: String,
    upstream_commit: String,
    upstream_dictionary_path: String,
    source_sha256: String,
    fetched_at_utc: String,
}

#[derive(Debug, Clone, Copy)]
enum Charset {
    N,
    X,
    Y,
    Z,
}

#[derive(Debug, Clone)]
struct Component {
    charset: Charset,
    min: u8,
    max: u8,
    optional: bool,
    mod10_check: bool,
    date_rule: DateRule,
    time_rule: TimeRule,
}

#[derive(Debug, Clone, Copy)]
enum DateRule {
    None,
    YymmddStrict,
    YymmddAllowZeroDay,
}

#[derive(Debug, Clone, Copy)]
enum TimeRule {
    None,
    Hhmi,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let source = manifest_dir.join("data/gs1-syntax-dictionary.txt");
    let lock_path = manifest_dir.join("data/gs1-syntax-dictionary.lock.json");
    println!("cargo:rerun-if-changed={}", source.display());
    println!("cargo:rerun-if-changed={}", lock_path.display());

    let input = fs::read_to_string(&source).expect("read gs1 dictionary");
    let lock: DictionaryLock = serde_json::from_str(
        &fs::read_to_string(&lock_path).expect("read gs1 dictionary lock metadata"),
    )
    .expect("parse gs1 dictionary lock metadata");
    verify_dictionary_checksum(input.as_bytes(), &lock.source_sha256);
    let mut table = BTreeMap::<String, Meta>::new();

    for raw_line in input.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let mut split = line.splitn(2, '#');
        let body = split.next().unwrap_or_default().trim();
        let title = split
            .next()
            .map(str::trim)
            .filter(|v| !v.is_empty())
            .map(str::to_owned);
        if body.is_empty() {
            continue;
        }

        let tokens: Vec<&str> = body.split_whitespace().collect();
        if tokens.len() < 2 {
            continue;
        }

        let ai_token = tokens[0];
        let (flags, body_start) = if tokens[1].chars().all(|c| !c.is_ascii_alphanumeric()) {
            (tokens[1], 2)
        } else {
            ("", 1)
        };
        if tokens.len() <= body_start {
            continue;
        }

        let mut spec_tokens = Vec::new();
        let mut attr_tokens = Vec::new();
        for t in &tokens[body_start..] {
            let is_attr = t == &"dlpkey" || t.contains('=');
            if is_attr || !attr_tokens.is_empty() {
                attr_tokens.push(*t);
            } else {
                spec_tokens.push(*t);
            }
        }
        if spec_tokens.is_empty() {
            continue;
        }

        let spec = spec_tokens.join(" ");
        let attrs = attr_tokens.join(" ");
        let fixed_len = fixed_len_from_spec(&spec);
        let components = parse_components(&spec);
        if components.is_empty() {
            continue;
        }
        let dl_primary_key = attrs.contains("dlpkey");
        let dl_qualifiers = attrs
            .split_whitespace()
            .find_map(|a| a.strip_prefix("dlpkey=").map(str::to_owned));
        let req_groups = attrs
            .split_whitespace()
            .filter_map(|a| a.strip_prefix("req="))
            .map(parse_req_clause)
            .collect::<Vec<_>>();
        let ex_groups = attrs
            .split_whitespace()
            .filter_map(|a| a.strip_prefix("ex="))
            .flat_map(|v| {
                v.split(',')
                    .filter(|p| !p.is_empty())
                    .map(str::to_owned)
                    .collect::<Vec<_>>()
            })
            .collect::<Vec<_>>();

        let meta = Meta {
            fixed_len,
            components,
            title,
            fnc1_required: !flags.contains('*'),
            dl_data_attr: flags.contains('?'),
            dl_primary_key,
            dl_qualifiers,
            req_rules: req_groups,
            ex_rules: ex_groups,
        };

        for ai in expand_ai(ai_token) {
            table.entry(ai).or_insert_with(|| meta.clone());
        }
    }

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from gs1-syntax-dictionary metadata.\n");
    out.push_str(&format!(
        "// Source repo: {}\n// Source ref: {}\n// Source commit: {}\n// Source path: {}\n// Source sha256: {}\n// Fetched at: {}\n\n",
        lock.upstream_repo,
        lock.upstream_ref,
        lock.upstream_commit,
        lock.upstream_dictionary_path,
        lock.source_sha256,
        lock.fetched_at_utc
    ));
    out.push_str(&format!(
        "pub const AI_DICTIONARY_SOURCE_REPO: &str = {:?};\n",
        lock.upstream_repo
    ));
    out.push_str(&format!(
        "pub const AI_DICTIONARY_SOURCE_REF: &str = {:?};\n",
        lock.upstream_ref
    ));
    out.push_str(&format!(
        "pub const AI_DICTIONARY_SOURCE_COMMIT: &str = {:?};\n",
        lock.upstream_commit
    ));
    out.push_str(&format!(
        "pub const AI_DICTIONARY_SOURCE_PATH: &str = {:?};\n",
        lock.upstream_dictionary_path
    ));
    out.push_str(&format!(
        "pub const AI_DICTIONARY_SOURCE_SHA256: &str = {:?};\n",
        lock.source_sha256
    ));
    out.push_str(&format!(
        "pub const AI_DICTIONARY_FETCHED_AT_UTC: &str = {:?};\n\n",
        lock.fetched_at_utc
    ));
    out.push_str("pub static AI_DICTIONARY: phf::Map<&'static str, AiMeta> = phf::phf_map! {\n");
    for (ai, m) in &table {
        let fixed = match m.fixed_len {
            Some(n) => format!("Some({n})"),
            None => "None".to_owned(),
        };
        let title = match &m.title {
            Some(v) => format!("Some({v:?})"),
            None => "None".to_owned(),
        };
        let quals = match &m.dl_qualifiers {
            Some(q) => format!("Some({q:?})"),
            None => "None".to_owned(),
        };
        let req = render_req_rules(&m.req_rules);
        let ex = render_ex_rules(&m.ex_rules);
        let components = m
            .components
            .iter()
            .map(|c| {
                let charset = match c.charset {
                    Charset::N => "AiCharset::N",
                    Charset::X => "AiCharset::X",
                    Charset::Y => "AiCharset::Y",
                    Charset::Z => "AiCharset::Z",
                };
                format!(
                    "AiComponent {{ charset: {charset}, min: {}, max: {}, optional: {}, mod10_check: {}, date_rule: {}, time_rule: {} }}",
                    c.min,
                    c.max,
                    c.optional,
                    c.mod10_check,
                    match c.date_rule {
                        DateRule::None => "AiDateRule::None",
                        DateRule::YymmddStrict => "AiDateRule::YymmddStrict",
                        DateRule::YymmddAllowZeroDay => "AiDateRule::YymmddAllowZeroDay",
                    },
                    match c.time_rule {
                        TimeRule::None => "AiTimeRule::None",
                        TimeRule::Hhmi => "AiTimeRule::Hhmi",
                    }
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "    {ai:?} => AiMeta {{ code: {ai:?}, title: {title}, fixed_len: {fixed}, components: &[{components}], fnc1_required: {}, dl_data_attr: {}, dl_primary_key: {}, dl_qualifiers: {}, req_rules: {}, ex_rules: {} }},\n",
            m.fnc1_required, m.dl_data_attr, m.dl_primary_key, quals, req, ex
        ));
    }
    out.push_str("};\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("ai_dictionary.rs");
    fs::write(out_path, out).expect("write generated ai dictionary");
}

fn parse_components(spec: &str) -> Vec<Component> {
    let mut out = Vec::new();
    for token in spec.split_whitespace() {
        let mut head = token;
        let mut modifiers = "";
        if let Some((prefix, tail)) = head.split_once(',') {
            head = prefix;
            modifiers = tail;
        }
        if head.is_empty() {
            continue;
        }

        let optional = head.starts_with('[');
        let head = head.trim_start_matches('[').trim_end_matches(']');
        if head.len() < 2 {
            return Vec::new();
        }

        let charset = match head.as_bytes()[0] {
            b'N' => Charset::N,
            b'X' => Charset::X,
            b'Y' => Charset::Y,
            b'Z' => Charset::Z,
            _ => return Vec::new(),
        };

        let len_spec = &head[1..];
        let (min, max) = if let Some((_, max)) = len_spec.split_once("..") {
            let max = max.parse::<u8>().ok();
            (1u8, max.unwrap_or(0))
        } else {
            let n = len_spec.parse::<u8>().ok();
            (n.unwrap_or(0), n.unwrap_or(0))
        };
        if min == 0 || max == 0 || min > max {
            return Vec::new();
        }
        let mod10_check = modifiers.split(',').any(|m| m == "csum");
        let date_rule = if modifiers.split(',').any(|m| m == "yymmdd") {
            DateRule::YymmddStrict
        } else if modifiers.split(',').any(|m| m == "yymmd0") {
            DateRule::YymmddAllowZeroDay
        } else {
            DateRule::None
        };
        let time_rule = if modifiers.split(',').any(|m| m == "hhmi") {
            TimeRule::Hhmi
        } else {
            TimeRule::None
        };
        out.push(Component {
            charset,
            min,
            max,
            optional,
            mod10_check,
            date_rule,
            time_rule,
        });
    }
    out
}

fn expand_ai(token: &str) -> Vec<String> {
    if let Some((start, end)) = token.split_once('-') {
        if let (Ok(a), Ok(b)) = (start.parse::<u32>(), end.parse::<u32>()) {
            let width = start.len();
            return (a..=b).map(|n| format!("{n:0width$}")).collect();
        }
    }
    vec![token.to_owned()]
}

fn fixed_len_from_spec(spec: &str) -> Option<u8> {
    let mut sum: u16 = 0;
    for part in spec.split_whitespace() {
        let mut p = part;
        if p.starts_with('[') {
            return None;
        }
        if let Some((head, _)) = p.split_once(',') {
            p = head;
        }
        if p.len() < 2 {
            return None;
        }
        let len = &p[1..];
        if len.contains("..") {
            return None;
        }
        let n = len.parse::<u16>().ok()?;
        sum = sum.checked_add(n)?;
    }
    u8::try_from(sum).ok()
}

fn parse_req_clause(s: &str) -> ReqClause {
    s.split(',')
        .filter(|g| !g.is_empty())
        .map(|group| {
            group
                .split('+')
                .filter(|p| !p.is_empty())
                .map(str::to_owned)
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>()
}

fn render_req_rules(rules: &[ReqClause]) -> String {
    if rules.is_empty() {
        return "&[]".to_owned();
    }
    let clauses = rules
        .iter()
        .map(|clause| {
            let groups = clause
                .iter()
                .map(|group| {
                    let parts = group
                        .iter()
                        .map(|p| format!("{p:?}"))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("AiReqGroup {{ all_of: &[{parts}] }}")
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("AiReqClause {{ any_of: &[{groups}] }}")
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("&[{clauses}]")
}

fn render_ex_rules(rules: &[String]) -> String {
    if rules.is_empty() {
        return "&[]".to_owned();
    }
    let items = rules
        .iter()
        .map(|r| format!("{r:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    format!("&[{items}]")
}

fn verify_dictionary_checksum(source_bytes: &[u8], expected_hex: &str) {
    let actual = Sha256::digest(source_bytes);
    let actual_hex = format!("{actual:x}");
    assert_eq!(
        actual_hex, expected_hex,
        "gs1 dictionary checksum mismatch: expected {expected_hex}, got {actual_hex}"
    );
}
